InfiniteLoops-main/orders/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :orders
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'orders#index'

  namespace :api do
    namespace :v1 do
      resources :orders do
      end
    end
  end
end

InfiniteLoops-main/orders/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

InfiniteLoops-main/orders/app/models/customer.rb
class Customer < ApplicationRecord
end

InfiniteLoops-main/orders/app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  belongs_to :customer
  has_many :product_orders
  has_many :products, through: :product_orders

  PROCESSING = 'processing'
  COMPLETE = 'complete'
  CANCELLED = 'cancelled'
end

InfiniteLoops-main/orders/app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  has_many :products_orders
  has_many :orders, through: :product_orders
end

InfiniteLoops-main/orders/app/models/product_order.rb
# frozen_string_literal: true

class ProductOrder < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

InfiniteLoops-main/orders/app/controllers/api/v1/orders_controller.rb
# frozen_string_literal: true

class Api::V1::OrdersController < ApplicationController
  before_action :find_order, only: [:show]
  skip_before_action :verify_authenticity_token

  # GET /api/v1/orders
  def index
    @orders = Order.all

    render json: @orders
  end

  def show
    render json: @order
  end

  def create
    @order = Order.new

    if order_params[:email].blank?
      render json: { error: 'Unable to create order. Missing email' }, status: 400
      return
    elsif order_params[:products].blank?
      render json: { error: 'Unable to create order. No products given' }, status: 400
      return
    end

    email = order_params[:email]
    first_name = order_params[:first_name]
    last_name = order_params[:last_name]

    @customer = Customer.find_by(email: email)

    if @customer.blank?
      @customer = Customer.new
      @customer.email = email
      @customer.first_name = first_name if first_name.present?
      @customer.last_name = last_name if last_name.present?

      unless @customer.save
        render json: { error: 'Unable to create new customer' }, status: 400
        return
      end
    end

    products = order_params[:products]

    @order.total = 100
    @order.customer = @customer
    @order.status = Order::PROCESSING

    if @order.save
      products.each do |product|
        productId = product.first.to_i
        product = Product.find_or_create_by(id: productId)
        @order.products << product
      end
    else
      render json: { error: 'Unable to create order' }, status: 400
      return
    end
    render json: { order: @order }, status: 200
  end

  private

  def find_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:first_name, :last_name, :email, products: {})
  end
end

InfiniteLoops-main/orders/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

InfiniteLoops-main/orders/app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  def index
    @orders = Order.all

    respond_to do |format|
      format.html
    end
  end

  def new; end

  def edit
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])

    if @order.update(order_params)
      redirect_to orders_path
    else
      render 'edit'
    end
  end

  private

  def order_params
    params.require(:order).permit(:customer_id, :status, :total)
  end
end

InfiniteLoops-main/orders/app/helpers/api/v1/orders_helper.rb
module Api::V1::OrdersHelper
end

InfiniteLoops-main/orders/app/helpers/application_helper.rb
module ApplicationHelper
end

InfiniteLoops-main/orders/app/helpers/orders_helper.rb
module OrdersHelper
end

InfiniteLoops-main/orders/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

InfiniteLoops-main/orders/app/views/orders/edit.html.erb
<h1>Edit Order</h1>

<%= form_with(model: @order, local: true) do |form| %>

  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@order.errors.count, "error") %> kept us from updating
      </h2>

      <ul>
        <% @order.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :customer_id %><br>
    <%= form.text_field :customer_id %>
  </p>

  <p>
    <%= form.label :total %><br>
    <%= form.text_field :total %>
  </p>
        
  <p>
    <%= form.label :status %><br>
    <%= form.select :status, [Order::PROCESSING, Order::CANCELLED, Order::COMPLETE] %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

<%= link_to 'Back', orders_path %>

InfiniteLoops-main/orders/app/views/orders/index.html.erb
<h1>All Orders</h1>

<table>
  <tr>
    <th>Order ID</th>
    <th>Customer ID</th>
    <th>Total</th>
    <th>Status</th>
    <th />
  </tr>

  <% @orders.each do |order| %>
    <tr>
      <td><%= order.id %></td>
      <td><%= order.customer_id %></td>
      <td><%= order.total %></td>
      <td><%= order.status %></td>
      <td><%= link_to 'edit', edit_order_path(order) %></td>
    </tr>
  <% end %>
</table>